CMDCT-5271 lots of consolidation and shifting in deploy.yml and nearby

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,38 +13,18 @@ concurrency:
 
 permissions:
   id-token: write
-  contents: read
+  contents: write
   actions: read
 
+env:
+  PROJECT: ${{ vars.APP_NAME_LOWER }}
+
 jobs:
-  unit-tests:
-    name: Unit Tests
-    uses: ./.github/workflows/unittest-workflow.yml
-    secrets:
-      CODE_CLIMATE_ID: ${{ secrets.CODE_CLIMATE_ID }}
   deploy:
     runs-on: ubuntu-latest
+    environment: ${{ (github.ref_name == 'production' && 'production') || (github.ref_name == 'val' && 'val') || 'dev' }}
     steps:
       - uses: actions/checkout@v4
-      - name: set branch_name # Some integrations (Dependabot & Snyk) build very long branch names. This is a switch to make long branch names shorter.
-        run: |
-          BRANCH_NAME=$(./.github/setBranchName.sh ${{ github.ref_name }})
-          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
-      - name: Validate branch name
-        run: ./.github/branchNameValidation.sh $branch_name
-      - name: set branch specific variable names
-        run: ./.github/buildVars.sh set_names
-      - name: set variable values
-        run: ./.github/buildVars.sh set_values
-        env:
-          AWS_DEFAULT_REGION: us-east-1
-          AWS_OIDC_ROLE_TO_ASSUME: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
-          CODE_CLIMATE_ID: ${{ secrets.CODE_CLIMATE_ID }}
-      - name: Configure AWS credentials for GitHub Actions
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ env.AWS_OIDC_ROLE_TO_ASSUME }}
-          aws-region: ${{ env.AWS_DEFAULT_REGION }}
       - uses: actions/setup-node@v4
         with:
           node-version-file: ".nvmrc"
@@ -52,18 +32,21 @@ jobs:
         with:
           path: "**/node_modules"
           key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
-      - name: set path
+      - name: path + branch settings + install packages
         run: |
           echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
+          BRANCH_NAME=$(./.github/setBranchName.sh ${{ github.ref_name }})
+          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
+          ./.github/branchNameValidation.sh $branch_name
+          ./run install
+      - name: Configure AWS credentials for GitHub Actions
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
+          aws-region: us-east-1
       - name: deploy
-        run: |
-          # When deploying multiple copies of this quickstart to the same AWS Account (not ideal), a prefix helps prevent stepping on each other.
-          # This can optionally be set as an GitHub Actions Secret
-          ./run deploy --stage $branch_name
-        env:
-          PROJECT: ${{ vars.APP_NAME_LOWER }}
-      - name: Endpoint
-        id: endpoint
+        run: ./run deploy --stage $branch_name
+      - id: endpoint
         run: |
           APPLICATION_ENDPOINT=$(./scripts/output.sh qmr-$branch_name CloudFrontUrl)
           echo "application_endpoint=$APPLICATION_ENDPOINT" >> $GITHUB_OUTPUT
@@ -71,11 +54,10 @@ jobs:
           echo "<$APPLICATION_ENDPOINT>" >> $GITHUB_STEP_SUMMARY
     outputs:
       application_endpoint: ${{ steps.endpoint.outputs.application_endpoint }}
-      BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION: ${{ steps.set_names.outputs.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION }}
-      BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME: ${{ steps.set_names.outputs.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME }}
 
   register-runner:
     name: Register GitHub Runner
+    environment: ${{ (github.ref_name == 'production' && 'production') || (github.ref_name == 'val' && 'val') || 'dev' }}
     if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' }}
     runs-on: ubuntu-latest
     needs: deploy
@@ -88,32 +70,13 @@ jobs:
           BRANCH_NAME=$(./.github/setBranchName.sh ${{ github.ref_name }})
           echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
 
-      - name: set branch specific variable names
-        id: set_names
-        run: ./.github/buildVars.sh set_names
-
-      - name: set variable values
-        id: set_values
-        run: ./.github/buildVars.sh set_values
-        env:
-          AWS_DEFAULT_REGION: us-east-1
-          AWS_OIDC_ROLE_TO_ASSUME: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
-
       - name: Configure AWS credentials for GitHub Actions
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
           aws-region: us-east-1
 
-      - name: output account id
-        id: output_account_id
-        run: |
-          #!/bin/bash
-          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
-          echo "Current Account ID: ${AWS_ACCOUNT_ID}"
-
-      - name: Get Github Actions CIDR Blocks
-        id: get-gha-cidrs
+      - id: shell-steps
         shell: bash
         run: |
           #!/bin/bash
@@ -122,28 +85,14 @@ jobs:
           IPV4_CIDR_ARR=($(echo $GHA_RESP | jq -r '.actions | .[]' | grep -v ':'))
           GHA_CIDRS_IPV4=$(echo $(IFS=" "; echo ${IPV4_CIDR_ARR[*]}))
           echo "GHA_CIDRS_IPV4=$GHA_CIDRS_IPV4" >> $GITHUB_OUTPUT
-
-      - name: Generate IP Set Name
-        id: gen-ip-set-name
-        run: |
-          #!/bin/bash
           STAGE_GH_IPSET_NAME=$branch_name-gh-ipset
           echo "Github IP Set name:  $STAGE_GH_IPSET_NAME"
           echo "STAGE_GH_IPSET_NAME=$STAGE_GH_IPSET_NAME" >> $GITHUB_OUTPUT
-
-      - name: Fetch AWS IP Set Metadata
-        id: fetch-ip-set-info
-        run: |
-          #!/bin/bash
-          # Fetch AWS IP set ARNs using AWS CLI and store them in a variable
           AWS_IP_SET_INFO=$(aws wafv2 list-ip-sets --scope=CLOUDFRONT)
           echo "Outputting AWS IP Set Info:  ${AWS_IP_SET_INFO}"
-          # Store the IP set ARNs in an output variable using GITHUB_OUTPUT
-          IPSET_NAME=${{ steps.gen-ip-set-name.outputs.STAGE_GH_IPSET_NAME }}
+          IPSET_NAME=$STAGE_GH_IPSET_NAME
           IPSET=$(jq '.IPSets | map(select(.Name == "'${IPSET_NAME}'")) | .[]' <<< ${AWS_IP_SET_INFO})
           [ -z "$IPSET" ] && echo "IP Set with name ${IPSET_NAME} was not located.  Exiting..." && exit 1
-          echo "IP Set metadata:  ${IPSET}"
-          #Get Values from the IP SET
           IPSET_ID=$(jq -r '.Id' <<< ${IPSET})
           echo "IPSET_ARN=$IPSET_ARN" >> $GITHUB_OUTPUT
           echo "IPSET_NAME=$IPSET_NAME" >> $GITHUB_OUTPUT
@@ -151,18 +100,15 @@ jobs:
 
       - name: Update IP Set
         id: update-ip-set
-        run: ./.github/wafController.sh set ${{ steps.fetch-ip-set-info.outputs.IPSET_NAME }} ${{ steps.fetch-ip-set-info.outputs.IPSET_ID }} ${{ steps.get-gha-cidrs.outputs.GHA_CIDRS_IPV4 }}
-        env:
-          AWS_RETRY_MODE: adaptive
-          AWS_MAX_ATTEMPTS: 10
-
+        run: ./.github/wafController.sh set ${{ steps.shell-steps.outputs.IPSET_NAME }} ${{ steps.shell-steps.outputs.IPSET_ID }} ${{ steps.shell-steps.outputs.GHA_CIDRS_IPV4 }}
     outputs:
-      ipset_name: ${{ steps.fetch-ip-set-info.outputs.IPSET_NAME }}
-      ipset_id: ${{ steps.fetch-ip-set-info.outputs.IPSET_ID }}
+      ipset_name: ${{ steps.shell-steps.outputs.IPSET_NAME }}
+      ipset_id: ${{ steps.shell-steps.outputs.IPSET_ID }}
 
   e2e-tests-init:
     name: Initialize End To End Tests
-    if: ${{ always() && !cancelled() && needs.deploy.result == 'success' && github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' }}
+    if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' }}
+    environment: ${{ (github.ref_name == 'production' && 'production') || (github.ref_name == 'val' && 'val') || 'dev' }}
     needs:
       - deploy
       - register-runner
@@ -178,15 +124,6 @@ jobs:
         run: |
           BRANCH_NAME=$(./.github/setBranchName.sh ${{ github.ref_name }})
           echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
-      - name: set branch specific variable names
-        id: set_names
-        run: ./.github/buildVars.sh set_names
-      - name: set variable values
-        id: set_values
-        run: ./.github/buildVars.sh set_values
-        env:
-          AWS_DEFAULT_REGION: us-east-1
-          AWS_OIDC_ROLE_TO_ASSUME: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
       - uses: actions/setup-node@v4
         with:
           node-version-file: ".nvmrc"
@@ -206,49 +143,88 @@ jobs:
       - name: Configure AWS credentials for GitHub Actions
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: ${{ env.AWS_OIDC_ROLE_TO_ASSUME }}
-          aws-region: ${{ env.AWS_DEFAULT_REGION }}
+          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
+          aws-region: us-east-1
       - name: Install dependencies
         run: yarn install --frozen-lockfile
       - name: set path
         run: |
           echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
-    outputs:
-      application_endpoint: ${{ needs.deploy.outputs.application_endpoint }}
 
-  e2e-tests:
-    name: "Run End To End Tests"
-    uses: ./.github/workflows/cypress-workflow.yml
-    needs:
-      - e2e-tests-init
-    with:
-      test-path: "e2e"
-      test-endpoint: "${{ needs.e2e-tests-init.outputs.application_endpoint }}"
-    secrets:
-      cypress-user2: ${{ secrets.CYPRESS_STATE_USER_2 }}
-      cypress-user4: ${{ secrets.CYPRESS_STATE_USER_4 }}
-      cypress-admin-user: ${{ secrets.CYPRESS_ADMIN_USER }}
-      cypress-password: ${{ secrets.CYPRESS_QMR_PASSWORD }}
-
-  cleanup:
-    name: Delist GHA Runner CIDR Blocks
+  e2e-tests-setup:
+    name: "Set up Matrix End To End Tests"
     if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' }}
     runs-on: ubuntu-latest
     needs:
       - deploy
       - e2e-tests-init
-      - e2e-tests
-      - register-runner
     steps:
       - uses: actions/checkout@v4
-      - name: Configure AWS credentials for GitHub Actions
-        uses: aws-actions/configure-aws-credentials@v4
+      - id: set-test-matrix
+        run: |
+          TEST_MATRIX=$(ls -1 tests/cypress/cypress/e2e/* | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
+          echo "Test definitions: ${TEST_MATRIX}"
+          [ $(jq length <<< "${TEST_MATRIX}") -lt 1 ] && echo "No test definition found...exiting" && exit 1
+          echo "test-matrix=${TEST_MATRIX}" >> $GITHUB_OUTPUT
+    outputs:
+      test-matrix: ${{ steps.set-test-matrix.outputs.test-matrix }}
+
+  e2e-tests:
+    name: Execute Cypress Tests
+    if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' }}
+    runs-on: ubuntu-latest
+    needs:
+      - deploy
+      - e2e-tests-setup
+    strategy:
+      fail-fast: false
+      matrix:
+        containers: ${{ fromJson(needs.e2e-tests-setup.outputs.test-matrix) }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install dependencies
+        run: yarn install --frozen-lockfile
+      - name: set path
+        run: |
+          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
+      - name: Run Cypress Tests
+        uses: cypress-io/github-action@v6
         with:
-          role-to-assume: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME] || secrets.AWS_OIDC_ROLE_TO_ASSUME }}
-          aws-region: us-east-1
-      - name: clean-up-iplist
-        id: reset-ip-set
-        run: ./.github/wafController.sh set ${{ needs.register-runner.outputs.ipset_name }} ${{ needs.register-runner.outputs.ipset_id }} '[]'
+          working-directory: tests/cypress
+          spec: cypress/e2e/${{ matrix.containers }}
+          browser: chrome
+          headed: true
+          config: baseUrl=${{ needs.deploy.outputs.application_endpoint }}
+          env: true
         env:
-          AWS_RETRY_MODE: adaptive
-          AWS_MAX_ATTEMPTS: 10
+          CYPRESS_STATE_USER_2: ${{ secrets.CYPRESS_STATE_USER_2 }}
+          CYPRESS_STATE_USER_4: ${{ secrets.CYPRESS_STATE_USER_4 }}
+          CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}
+          CYPRESS_QMR_PASSWORD: ${{ secrets.CYPRESS_QMR_PASSWORD }}
+      - name: Upload screenshots
+        uses: actions/upload-artifact@v4
+        if: failure()
+        with:
+          name: ${{ matrix.containers }}-test-results
+          path: tests/cypress/screenshots/
+          retention-days: 14
+
+  # cleanup:
+  #   name: Delist GHA Runner CIDR Blocks
+  #   if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' }}
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - deploy
+  #     - e2e-tests-init
+  #     - e2e-tests
+  #     - register-runner
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Configure AWS credentials for GitHub Actions
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
+  #         aws-region: us-east-1
+  #     - name: clean-up-iplist
+  #       id: reset-ip-set
+  #       run: ./.github/wafController.sh set ${{ needs.register-runner.outputs.ipset_name }} ${{ needs.register-runner.outputs.ipset_id }} '[]'
